configured_endpoints: 1709
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/cloudflare%2Fcloudflare-9a6c15859ccc10f2ec73e216adea1cc72a454eeefa5c4aa0db549aa1b9cf5420.yml
openapi_spec_hash: e7af7e95b8f44d1c03394cbfca1ee5a7
config_hash: a0dfdc5bed4f8f58209af089db514d49
