// File generated from our OpenAPI spec by Stainless.

package cloudflare

import (
	"context"
	"fmt"
	"net/http"

	"github.com/cloudflare/cloudflare-sdk-go/internal/apijson"
	"github.com/cloudflare/cloudflare-sdk-go/internal/param"
	"github.com/cloudflare/cloudflare-sdk-go/internal/requestconfig"
	"github.com/cloudflare/cloudflare-sdk-go/option"
)

// AccountAIService contains methods and other services that help with interacting
// with the cloudflare API. Note, unlike clients, this service does not read
// variables from the environment automatically. You should not instantiate this
// service directly, and instead use the [NewAccountAIService] method instead.
type AccountAIService struct {
	Options []option.RequestOption
}

// NewAccountAIService generates a new service that applies the given options to
// each request. These options are applied after the parent client's options (if
// there is one), and before any request-specific options.
func NewAccountAIService(opts ...option.RequestOption) (r *AccountAIService) {
	r = &AccountAIService{}
	r.Options = opts
	return
}

// This endpoint provides users with the capability to run specific AI models
// on-demand.
//
// By submitting the required input data, users can receive real-time predictions
// or results generated by the chosen AI model. The endpoint supports various AI
// model types, ensuring flexibility and adaptability for diverse use cases.
func (r *AccountAIService) Run(ctx context.Context, accountIdentifier string, modelName string, body AccountAIRunParams, opts ...option.RequestOption) (res *AccountAIRunResponse, err error) {
	opts = append(r.Options[:], opts...)
	path := fmt.Sprintf("accounts/%s/ai/run/%s", accountIdentifier, modelName)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return
}

type AccountAIRunResponse struct {
	Errors   []AccountAIRunResponseError `json:"errors,required"`
	Messages []string                    `json:"messages,required"`
	Result   interface{}                 `json:"result,required"`
	Success  bool                        `json:"success,required"`
	JSON     accountAIRunResponseJSON    `json:"-"`
}

// accountAIRunResponseJSON contains the JSON metadata for the struct
// [AccountAIRunResponse]
type accountAIRunResponseJSON struct {
	Errors      apijson.Field
	Messages    apijson.Field
	Result      apijson.Field
	Success     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *AccountAIRunResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

type AccountAIRunResponseError struct {
	Message string                        `json:"message,required"`
	JSON    accountAIRunResponseErrorJSON `json:"-"`
}

// accountAIRunResponseErrorJSON contains the JSON metadata for the struct
// [AccountAIRunResponseError]
type accountAIRunResponseErrorJSON struct {
	Message     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *AccountAIRunResponseError) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

type AccountAIRunParams struct {
	Body param.Field[interface{}] `json:"body,required"`
}

func (r AccountAIRunParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.Body)
}
