package cloudflare

//go:generate rm -vf interface.go

//go:generate ifacemaker -s=API -p=cloudflare -i=APIV4 -f=*.go -y "APIV4 provides the interface for the Cloudflare V4 API" -c "Code generated by ifacemaker (via make interface) DO NOT EDIT" -o interface.go
