blank_issues_enabled: false
contact_links:
  - name: Cloudflare support
    url: https://developers.cloudflare.com/support/contacting-cloudflare-support
    about: |
      Please only file issues here that you believe represent actual bugs for the Cloudflare Go library.
      If you're having general trouble with the Cloudflare API, please visit our help center to get support.
