// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package zero_trust

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/cloudflare/cloudflare-go/v7/internal/apijson"
	"github.com/cloudflare/cloudflare-go/v7/internal/apiquery"
	"github.com/cloudflare/cloudflare-go/v7/internal/param"
	"github.com/cloudflare/cloudflare-go/v7/internal/requestconfig"
	"github.com/cloudflare/cloudflare-go/v7/option"
	"github.com/cloudflare/cloudflare-go/v7/packages/pagination"
)

// CasbPostureExportService contains methods and other services that help with
// interacting with the cloudflare API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewCasbPostureExportService] method instead.
type CasbPostureExportService struct {
	Options []option.RequestOption
}

// NewCasbPostureExportService generates a new service that applies the given
// options to each request. These options are applied after the parent client's
// options (if there is one), and before any request-specific options.
func NewCasbPostureExportService(opts ...option.RequestOption) (r *CasbPostureExportService) {
	r = &CasbPostureExportService{}
	r.Options = opts
	return
}

// List all export jobs for a given requestor's organization
func (r *CasbPostureExportService) List(ctx context.Context, params CasbPostureExportListParams, opts ...option.RequestOption) (res *pagination.V4PagePaginationArray[CasbPostureExportListResponse], err error) {
	var raw *http.Response
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithResponseInto(&raw)}, opts...)
	if params.AccountID.Value == "" {
		err = errors.New("missing required account_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("accounts/%s/data-security/posture/exports", params.AccountID)
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, path, params, &res, opts...)
	if err != nil {
		return nil, err
	}
	err = cfg.Execute()
	if err != nil {
		return nil, err
	}
	res.SetPageConfig(cfg, raw)
	return res, nil
}

// List all export jobs for a given requestor's organization
func (r *CasbPostureExportService) ListAutoPaging(ctx context.Context, params CasbPostureExportListParams, opts ...option.RequestOption) *pagination.V4PagePaginationArrayAutoPager[CasbPostureExportListResponse] {
	return pagination.NewV4PagePaginationArrayAutoPager(r.List(ctx, params, opts...))
}

// Retrieves a single export job by its unique identifier
func (r *CasbPostureExportService) Get(ctx context.Context, id string, query CasbPostureExportGetParams, opts ...option.RequestOption) (res *CasbPostureExportGetResponse, err error) {
	var env CasbPostureExportGetResponseEnvelope
	opts = slices.Concat(r.Options, opts)
	if query.AccountID.Value == "" {
		err = errors.New("missing required account_id parameter")
		return nil, err
	}
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("accounts/%s/data-security/posture/exports/%s", query.AccountID, id)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &env, opts...)
	if err != nil {
		return nil, err
	}
	res = &env.Result
	return res, nil
}

// Information about an export job.
type CasbPostureExportListResponse struct {
	// Unique identifier for the export job.
	ID string `json:"id" api:"required" format:"uuid"`
	// Status of an export job.
	Status CasbPostureExportListResponseStatus `json:"status" api:"required"`
	// Type of export job.
	Type CasbPostureExportListResponseType `json:"type" api:"required"`
	// ID of the export-requesting user.
	UserID string `json:"user_id" api:"required"`
	// The URL by which the successfully created export can be downloaded by the end
	// users.
	DownloadURL string `json:"download_url" api:"nullable" format:"uri"`
	// Contains information on errors which may have occurred during export creation.
	Errors string `json:"errors" api:"nullable"`
	// The base name of the file that is/was generated by the export job.
	FileName string `json:"file_name" api:"nullable"`
	// The full path of the file that is stored within external storage (currently R2).
	FilePath string                            `json:"file_path" api:"nullable"`
	JSON     casbPostureExportListResponseJSON `json:"-"`
}

// casbPostureExportListResponseJSON contains the JSON metadata for the struct
// [CasbPostureExportListResponse]
type casbPostureExportListResponseJSON struct {
	ID          apijson.Field
	Status      apijson.Field
	Type        apijson.Field
	UserID      apijson.Field
	DownloadURL apijson.Field
	Errors      apijson.Field
	FileName    apijson.Field
	FilePath    apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *CasbPostureExportListResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r casbPostureExportListResponseJSON) RawJSON() string {
	return r.raw
}

// Status of an export job.
type CasbPostureExportListResponseStatus string

const (
	CasbPostureExportListResponseStatusPending     CasbPostureExportListResponseStatus = "Pending"
	CasbPostureExportListResponseStatusSuccess     CasbPostureExportListResponseStatus = "Success"
	CasbPostureExportListResponseStatusFailure     CasbPostureExportListResponseStatus = "Failure"
	CasbPostureExportListResponseStatusRescheduled CasbPostureExportListResponseStatus = "Rescheduled"
	CasbPostureExportListResponseStatusInProgress  CasbPostureExportListResponseStatus = "In-Progress"
)

func (r CasbPostureExportListResponseStatus) IsKnown() bool {
	switch r {
	case CasbPostureExportListResponseStatusPending, CasbPostureExportListResponseStatusSuccess, CasbPostureExportListResponseStatusFailure, CasbPostureExportListResponseStatusRescheduled, CasbPostureExportListResponseStatusInProgress:
		return true
	}
	return false
}

// Type of export job.
type CasbPostureExportListResponseType string

const (
	CasbPostureExportListResponseTypeFinding         CasbPostureExportListResponseType = "finding"
	CasbPostureExportListResponseTypeFindingInstance CasbPostureExportListResponseType = "findingInstance"
	CasbPostureExportListResponseTypeContent         CasbPostureExportListResponseType = "content"
	CasbPostureExportListResponseTypeRemediationJob  CasbPostureExportListResponseType = "remediationJob"
)

func (r CasbPostureExportListResponseType) IsKnown() bool {
	switch r {
	case CasbPostureExportListResponseTypeFinding, CasbPostureExportListResponseTypeFindingInstance, CasbPostureExportListResponseTypeContent, CasbPostureExportListResponseTypeRemediationJob:
		return true
	}
	return false
}

// Information about an export job.
type CasbPostureExportGetResponse struct {
	// Unique identifier for the export job.
	ID string `json:"id" api:"required" format:"uuid"`
	// Status of an export job.
	Status CasbPostureExportGetResponseStatus `json:"status" api:"required"`
	// Type of export job.
	Type CasbPostureExportGetResponseType `json:"type" api:"required"`
	// ID of the export-requesting user.
	UserID string `json:"user_id" api:"required"`
	// The URL by which the successfully created export can be downloaded by the end
	// users.
	DownloadURL string `json:"download_url" api:"nullable" format:"uri"`
	// Contains information on errors which may have occurred during export creation.
	Errors string `json:"errors" api:"nullable"`
	// The base name of the file that is/was generated by the export job.
	FileName string `json:"file_name" api:"nullable"`
	// The full path of the file that is stored within external storage (currently R2).
	FilePath string                           `json:"file_path" api:"nullable"`
	JSON     casbPostureExportGetResponseJSON `json:"-"`
}

// casbPostureExportGetResponseJSON contains the JSON metadata for the struct
// [CasbPostureExportGetResponse]
type casbPostureExportGetResponseJSON struct {
	ID          apijson.Field
	Status      apijson.Field
	Type        apijson.Field
	UserID      apijson.Field
	DownloadURL apijson.Field
	Errors      apijson.Field
	FileName    apijson.Field
	FilePath    apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *CasbPostureExportGetResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r casbPostureExportGetResponseJSON) RawJSON() string {
	return r.raw
}

// Status of an export job.
type CasbPostureExportGetResponseStatus string

const (
	CasbPostureExportGetResponseStatusPending     CasbPostureExportGetResponseStatus = "Pending"
	CasbPostureExportGetResponseStatusSuccess     CasbPostureExportGetResponseStatus = "Success"
	CasbPostureExportGetResponseStatusFailure     CasbPostureExportGetResponseStatus = "Failure"
	CasbPostureExportGetResponseStatusRescheduled CasbPostureExportGetResponseStatus = "Rescheduled"
	CasbPostureExportGetResponseStatusInProgress  CasbPostureExportGetResponseStatus = "In-Progress"
)

func (r CasbPostureExportGetResponseStatus) IsKnown() bool {
	switch r {
	case CasbPostureExportGetResponseStatusPending, CasbPostureExportGetResponseStatusSuccess, CasbPostureExportGetResponseStatusFailure, CasbPostureExportGetResponseStatusRescheduled, CasbPostureExportGetResponseStatusInProgress:
		return true
	}
	return false
}

// Type of export job.
type CasbPostureExportGetResponseType string

const (
	CasbPostureExportGetResponseTypeFinding         CasbPostureExportGetResponseType = "finding"
	CasbPostureExportGetResponseTypeFindingInstance CasbPostureExportGetResponseType = "findingInstance"
	CasbPostureExportGetResponseTypeContent         CasbPostureExportGetResponseType = "content"
	CasbPostureExportGetResponseTypeRemediationJob  CasbPostureExportGetResponseType = "remediationJob"
)

func (r CasbPostureExportGetResponseType) IsKnown() bool {
	switch r {
	case CasbPostureExportGetResponseTypeFinding, CasbPostureExportGetResponseTypeFindingInstance, CasbPostureExportGetResponseTypeContent, CasbPostureExportGetResponseTypeRemediationJob:
		return true
	}
	return false
}

type CasbPostureExportListParams struct {
	AccountID param.Field[string] `path:"account_id" api:"required"`
	// A page number within the paginated result set.
	Page param.Field[int64] `query:"page"`
	// Number of results to return per page.
	PerPage param.Field[int64] `query:"per_page"`
	// Filter on export job's status
	Status param.Field[CasbPostureExportListParamsStatus] `query:"status"`
}

// URLQuery serializes [CasbPostureExportListParams]'s query parameters as
// `url.Values`.
func (r CasbPostureExportListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatDots,
	})
}

// Filter on export job's status
type CasbPostureExportListParamsStatus string

const (
	CasbPostureExportListParamsStatusPending     CasbPostureExportListParamsStatus = "Pending"
	CasbPostureExportListParamsStatusSuccess     CasbPostureExportListParamsStatus = "Success"
	CasbPostureExportListParamsStatusFailure     CasbPostureExportListParamsStatus = "Failure"
	CasbPostureExportListParamsStatusRescheduled CasbPostureExportListParamsStatus = "Rescheduled"
	CasbPostureExportListParamsStatusInProgress  CasbPostureExportListParamsStatus = "In-Progress"
)

func (r CasbPostureExportListParamsStatus) IsKnown() bool {
	switch r {
	case CasbPostureExportListParamsStatusPending, CasbPostureExportListParamsStatusSuccess, CasbPostureExportListParamsStatusFailure, CasbPostureExportListParamsStatusRescheduled, CasbPostureExportListParamsStatusInProgress:
		return true
	}
	return false
}

type CasbPostureExportGetParams struct {
	AccountID param.Field[string] `path:"account_id" api:"required"`
}

// Common response structure for all API endpoints.
type CasbPostureExportGetResponseEnvelope struct {
	Errors   []CasbPostureExportGetResponseEnvelopeErrors   `json:"errors" api:"required"`
	Messages []CasbPostureExportGetResponseEnvelopeMessages `json:"messages" api:"required"`
	// Whether the API call was successful.
	Success bool `json:"success" api:"required"`
	// Information about an export job.
	Result CasbPostureExportGetResponse             `json:"result"`
	JSON   casbPostureExportGetResponseEnvelopeJSON `json:"-"`
}

// casbPostureExportGetResponseEnvelopeJSON contains the JSON metadata for the
// struct [CasbPostureExportGetResponseEnvelope]
type casbPostureExportGetResponseEnvelopeJSON struct {
	Errors      apijson.Field
	Messages    apijson.Field
	Success     apijson.Field
	Result      apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *CasbPostureExportGetResponseEnvelope) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r casbPostureExportGetResponseEnvelopeJSON) RawJSON() string {
	return r.raw
}

type CasbPostureExportGetResponseEnvelopeErrors struct {
	// Error or message code.
	Code int64 `json:"code" api:"required"`
	// Human-readable message.
	Message string `json:"message" api:"required"`
	// Link to relevant documentation.
	DocumentationURL string                                           `json:"documentation_url" format:"uri"`
	Source           CasbPostureExportGetResponseEnvelopeErrorsSource `json:"source"`
	JSON             casbPostureExportGetResponseEnvelopeErrorsJSON   `json:"-"`
}

// casbPostureExportGetResponseEnvelopeErrorsJSON contains the JSON metadata for
// the struct [CasbPostureExportGetResponseEnvelopeErrors]
type casbPostureExportGetResponseEnvelopeErrorsJSON struct {
	Code             apijson.Field
	Message          apijson.Field
	DocumentationURL apijson.Field
	Source           apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *CasbPostureExportGetResponseEnvelopeErrors) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r casbPostureExportGetResponseEnvelopeErrorsJSON) RawJSON() string {
	return r.raw
}

type CasbPostureExportGetResponseEnvelopeErrorsSource struct {
	// JSON pointer to the source of the error.
	Pointer string                                               `json:"pointer"`
	JSON    casbPostureExportGetResponseEnvelopeErrorsSourceJSON `json:"-"`
}

// casbPostureExportGetResponseEnvelopeErrorsSourceJSON contains the JSON metadata
// for the struct [CasbPostureExportGetResponseEnvelopeErrorsSource]
type casbPostureExportGetResponseEnvelopeErrorsSourceJSON struct {
	Pointer     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *CasbPostureExportGetResponseEnvelopeErrorsSource) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r casbPostureExportGetResponseEnvelopeErrorsSourceJSON) RawJSON() string {
	return r.raw
}

type CasbPostureExportGetResponseEnvelopeMessages struct {
	// Error or message code.
	Code int64 `json:"code" api:"required"`
	// Human-readable message.
	Message string `json:"message" api:"required"`
	// Link to relevant documentation.
	DocumentationURL string                                             `json:"documentation_url" format:"uri"`
	Source           CasbPostureExportGetResponseEnvelopeMessagesSource `json:"source"`
	JSON             casbPostureExportGetResponseEnvelopeMessagesJSON   `json:"-"`
}

// casbPostureExportGetResponseEnvelopeMessagesJSON contains the JSON metadata for
// the struct [CasbPostureExportGetResponseEnvelopeMessages]
type casbPostureExportGetResponseEnvelopeMessagesJSON struct {
	Code             apijson.Field
	Message          apijson.Field
	DocumentationURL apijson.Field
	Source           apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *CasbPostureExportGetResponseEnvelopeMessages) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r casbPostureExportGetResponseEnvelopeMessagesJSON) RawJSON() string {
	return r.raw
}

type CasbPostureExportGetResponseEnvelopeMessagesSource struct {
	// JSON pointer to the source of the error.
	Pointer string                                                 `json:"pointer"`
	JSON    casbPostureExportGetResponseEnvelopeMessagesSourceJSON `json:"-"`
}

// casbPostureExportGetResponseEnvelopeMessagesSourceJSON contains the JSON
// metadata for the struct [CasbPostureExportGetResponseEnvelopeMessagesSource]
type casbPostureExportGetResponseEnvelopeMessagesSourceJSON struct {
	Pointer     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *CasbPostureExportGetResponseEnvelopeMessagesSource) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r casbPostureExportGetResponseEnvelopeMessagesSourceJSON) RawJSON() string {
	return r.raw
}
