// File generated from our OpenAPI spec by Stainless.

package shared

type UnionString string

func (UnionString) ImplementsAccountUpdateResponse()                                              {}
func (UnionString) ImplementsAccountGetResponse()                                                 {}
func (UnionString) ImplementsAccountRoleGetResponse()                                             {}
func (UnionString) ImplementsCertificateNewResponse()                                             {}
func (UnionString) ImplementsCertificateGetResponse()                                             {}
func (UnionString) ImplementsMembershipUpdateResponse()                                           {}
func (UnionString) ImplementsMembershipGetResponse()                                              {}
func (UnionString) ImplementsUserEditResponse()                                                   {}
func (UnionString) ImplementsUserGetResponse()                                                    {}
func (UnionString) ImplementsUserAuditLogListResponse()                                           {}
func (UnionString) ImplementsUserBillingProfileGetResponse()                                      {}
func (UnionString) ImplementsUserInviteEditResponse()                                             {}
func (UnionString) ImplementsUserInviteGetResponse()                                              {}
func (UnionString) ImplementsUserLoadBalancerPoolHealthResponse()                                 {}
func (UnionString) ImplementsUserOrganizationGetResponse()                                        {}
func (UnionString) ImplementsUserSubscriptionUpdateResponse()                                     {}
func (UnionString) ImplementsUserSubscriptionEditResponse()                                       {}
func (UnionString) ImplementsUserTokenUpdateResponse()                                            {}
func (UnionString) ImplementsUserTokenGetResponse()                                               {}
func (UnionString) ImplementsZoneCustomNameserverUpdateResponse()                                 {}
func (UnionString) ImplementsZoneCustomNameserverGetResponse()                                    {}
func (UnionString) ImplementsZoneWorkerScriptUpdateResponse()                                     {}
func (UnionString) ImplementsZoneSubscriptionNewResponse()                                        {}
func (UnionString) ImplementsZoneSubscriptionGetResponse()                                        {}
func (UnionString) ImplementsLoadBalancerPoolHealthGetResponse()                                  {}
func (UnionString) ImplementsLoadBalancerRegionListResponse()                                     {}
func (UnionString) ImplementsLoadBalancerRegionGetResponse()                                      {}
func (UnionString) ImplementsCachePurgeParamsFile()                                               {}
func (UnionString) ImplementsCacheSmartTieredCachedDeleteResponse()                               {}
func (UnionString) ImplementsCacheSmartTieredCachedEditResponse()                                 {}
func (UnionString) ImplementsCacheSmartTieredCachedGetResponse()                                  {}
func (UnionString) ImplementsSSLAnalyzeNewResponse()                                              {}
func (UnionString) ImplementsSSLCertificatePackGetResponse()                                      {}
func (UnionString) ImplementsSubscriptionNewResponse()                                            {}
func (UnionString) ImplementsSubscriptionUpdateResponse()                                         {}
func (UnionString) ImplementsSubscriptionGetResponse()                                            {}
func (UnionString) ImplementsArgoSmartRoutingEditResponse()                                       {}
func (UnionString) ImplementsArgoSmartRoutingGetResponse()                                        {}
func (UnionString) ImplementsArgoTieredCachingEditResponse()                                      {}
func (UnionString) ImplementsArgoTieredCachingGetResponse()                                       {}
func (UnionString) ImplementsCustomCertificateNewResponse()                                       {}
func (UnionString) ImplementsCustomCertificateEditResponse()                                      {}
func (UnionString) ImplementsCustomCertificateGetResponse()                                       {}
func (UnionString) ImplementsCustomHostnameFallbackOriginUpdateResponse()                         {}
func (UnionString) ImplementsCustomHostnameFallbackOriginDeleteResponse()                         {}
func (UnionString) ImplementsCustomHostnameFallbackOriginGetResponse()                            {}
func (UnionString) ImplementsCustomNameserverDeleteResponse()                                     {}
func (UnionString) ImplementsDNSFirewallNewResponseDNSFirewallIP()                                {}
func (UnionString) ImplementsDNSFirewallNewResponseUpstreamIP()                                   {}
func (UnionString) ImplementsDNSFirewallListResponseDNSFirewallIP()                               {}
func (UnionString) ImplementsDNSFirewallListResponseUpstreamIP()                                  {}
func (UnionString) ImplementsDNSFirewallEditResponseDNSFirewallIP()                               {}
func (UnionString) ImplementsDNSFirewallEditResponseUpstreamIP()                                  {}
func (UnionString) ImplementsDNSFirewallGetResponseDNSFirewallIP()                                {}
func (UnionString) ImplementsDNSFirewallGetResponseUpstreamIP()                                   {}
func (UnionString) ImplementsDNSFirewallNewParamsUpstreamIP()                                     {}
func (UnionString) ImplementsDNSFirewallEditParamsDNSFirewallIP()                                 {}
func (UnionString) ImplementsDNSFirewallEditParamsUpstreamIP()                                    {}
func (UnionString) ImplementsDNSSECDeleteResponse()                                               {}
func (UnionString) ImplementsFirewallAccessRuleNewResponse()                                      {}
func (UnionString) ImplementsFirewallAccessRuleEditResponse()                                     {}
func (UnionString) ImplementsFirewallAccessRuleGetResponse()                                      {}
func (UnionString) ImplementsFirewallUARuleNewResponse()                                          {}
func (UnionString) ImplementsFirewallUARuleUpdateResponse()                                       {}
func (UnionString) ImplementsFirewallUARuleGetResponse()                                          {}
func (UnionString) ImplementsFirewallWAFPackageListResponseLegacyJhsAPIResponseCollectionResult() {}
func (UnionString) ImplementsFirewallWAFPackageGetResponseLegacyJhsAPIResponseSingleResult()      {}
func (UnionString) ImplementsFirewallWAFPackageGroupEditResponse()                                {}
func (UnionString) ImplementsFirewallWAFPackageGroupGetResponse()                                 {}
func (UnionString) ImplementsFirewallWAFPackageRuleGetResponse()                                  {}
func (UnionString) ImplementsLogpushJobDeleteResponse()                                           {}
func (UnionString) ImplementsLogControlCmbConfigDeleteResponse()                                  {}
func (UnionString) ImplementsLogRayidGetResponse()                                                {}
func (UnionString) ImplementsLogReceivedGetResponse()                                             {}
func (UnionString) ImplementsLogReceivedGetParamsEnd()                                            {}
func (UnionString) ImplementsLogReceivedGetParamsStart()                                          {}
func (UnionString) ImplementsOriginTLSClientAuthNewResponse()                                     {}
func (UnionString) ImplementsOriginTLSClientAuthDeleteResponse()                                  {}
func (UnionString) ImplementsOriginTLSClientAuthGetResponse()                                     {}
func (UnionString) ImplementsPageruleNewResponse()                                                {}
func (UnionString) ImplementsPageruleUpdateResponse()                                             {}
func (UnionString) ImplementsPageruleEditResponse()                                               {}
func (UnionString) ImplementsPageruleGetResponse()                                                {}
func (UnionString) ImplementsRateLimitNewResponse()                                               {}
func (UnionString) ImplementsRateLimitEditResponse()                                              {}
func (UnionString) ImplementsRateLimitGetResponse()                                               {}
func (UnionString) ImplementsWorkerScriptTailDeleteResponse()                                     {}
func (UnionString) ImplementsWorkerRouteNewResponse()                                             {}
func (UnionString) ImplementsWorkerRouteDeleteResponse()                                          {}
func (UnionString) ImplementsKVNamespaceUpdateResponse()                                          {}
func (UnionString) ImplementsKVNamespaceDeleteResponse()                                          {}
func (UnionString) ImplementsKVNamespaceBulkUpdateResponse()                                      {}
func (UnionString) ImplementsKVNamespaceBulkDeleteResponse()                                      {}
func (UnionString) ImplementsKVNamespaceValueUpdateResponse()                                     {}
func (UnionString) ImplementsKVNamespaceValueDeleteResponse()                                     {}
func (UnionString) ImplementsQueueDeleteResponse()                                                {}
func (UnionString) ImplementsQueueConsumerDeleteResponse()                                        {}
func (UnionString) ImplementsSpectrumAnalyticsEventBytimeGetResponse()                            {}
func (UnionString) ImplementsSpectrumAnalyticsEventSummaryGetResponse()                           {}
func (UnionString) ImplementsSpectrumAppNewResponseOriginPort()                                   {}
func (UnionString) ImplementsSpectrumAppUpdateResponseOriginPort()                                {}
func (UnionString) ImplementsSpectrumAppGetResponse()                                             {}
func (UnionString) ImplementsSpectrumAppNewParamsOriginPort()                                     {}
func (UnionString) ImplementsSpectrumAppUpdateParamsOriginPort()                                  {}
func (UnionString) ImplementsAddressingAddressMapDeleteResponse()                                 {}
func (UnionString) ImplementsAddressingAddressMapAccountUpdateResponse()                          {}
func (UnionString) ImplementsAddressingAddressMapAccountDeleteResponse()                          {}
func (UnionString) ImplementsAddressingAddressMapIPUpdateResponse()                               {}
func (UnionString) ImplementsAddressingAddressMapIPDeleteResponse()                               {}
func (UnionString) ImplementsAddressingAddressMapZoneUpdateResponse()                             {}
func (UnionString) ImplementsAddressingAddressMapZoneDeleteResponse()                             {}
func (UnionString) ImplementsAddressingPrefixDeleteResponse()                                     {}
func (UnionString) ImplementsAddressingPrefixBGPBindingDeleteResponse()                           {}
func (UnionString) ImplementsAuditLogListResponse()                                               {}
func (UnionString) ImplementsBillingProfileGetResponse()                                          {}
func (UnionString) ImplementsImageV1NewResponseVariant()                                          {}
func (UnionString) ImplementsImageV1ListResponseResultImagesVariant()                             {}
func (UnionString) ImplementsImageV1DeleteResponse()                                              {}
func (UnionString) ImplementsImageV1EditResponseVariant()                                         {}
func (UnionString) ImplementsImageV1GetResponseVariant()                                          {}
func (UnionString) ImplementsImageV1VariantDeleteResponse()                                       {}
func (UnionString) ImplementsImageV2ListResponseImagesVariant()                                   {}
func (UnionString) ImplementsIntelIPGetResponseIP()                                               {}
func (UnionString) ImplementsIntelMiscategorizationNewResponse()                                  {}
func (UnionString) ImplementsPageProjectNewResponse()                                             {}
func (UnionString) ImplementsPageProjectEditResponse()                                            {}
func (UnionString) ImplementsPageProjectDeploymentHistoryLogGetResponse()                         {}
func (UnionString) ImplementsPageProjectDomainNewResponse()                                       {}
func (UnionString) ImplementsPageProjectDomainEditResponse()                                      {}
func (UnionString) ImplementsPageProjectDomainGetResponse()                                       {}
func (UnionString) ImplementsRegistrarDomainUpdateResponse()                                      {}
func (UnionString) ImplementsRegistrarDomainGetResponse()                                         {}
func (UnionString) ImplementsRuleListItemGetResponse()                                            {}
func (UnionString) ImplementsStreamAudioTrackDeleteResponse()                                     {}
func (UnionString) ImplementsStreamKeyDeleteResponse()                                            {}
func (UnionString) ImplementsStreamWatermarkNewResponse()                                         {}
func (UnionString) ImplementsStreamWatermarkDeleteResponse()                                      {}
func (UnionString) ImplementsStreamWatermarkGetResponse()                                         {}
func (UnionString) ImplementsStreamWebhookUpdateResponse()                                        {}
func (UnionString) ImplementsStreamWebhookDeleteResponse()                                        {}
func (UnionString) ImplementsStreamWebhookGetResponse()                                           {}
func (UnionString) ImplementsStreamCaptionUpdateResponse()                                        {}
func (UnionString) ImplementsStreamCaptionDeleteResponse()                                        {}
func (UnionString) ImplementsStreamDownloadNewResponse()                                          {}
func (UnionString) ImplementsStreamDownloadDeleteResponse()                                       {}
func (UnionString) ImplementsStreamDownloadGetResponse()                                          {}
func (UnionString) ImplementsAlertingV3ListResponse()                                             {}
func (UnionString) ImplementsAlertingV3DestinationEligibleGetResponse()                           {}
func (UnionString) ImplementsAlertingV3DestinationPagerdutyDeleteResponse()                       {}
func (UnionString) ImplementsAlertingV3DestinationWebhookDeleteResponse()                         {}
func (UnionString) ImplementsAlertingV3PolicyListResponseMechanismsID()                           {}
func (UnionString) ImplementsAlertingV3PolicyDeleteResponse()                                     {}
func (UnionString) ImplementsAlertingV3PolicyGetResponseMechanismsID()                            {}
func (UnionString) ImplementsAlertingV3PolicyNewParamsMechanismsID()                              {}
func (UnionString) ImplementsAlertingV3PolicyUpdateParamsMechanismsID()                           {}
func (UnionString) ImplementsD1DatabaseDeleteResponse()                                           {}
func (UnionString) ImplementsWARPConnectorTokenResponse()                                         {}
func (UnionString) ImplementsZeroTrustDeviceGetResponse()                                         {}
func (UnionString) ImplementsZeroTrustDevicePostureIntegrationDeleteResponse()                    {}
func (UnionString) ImplementsZeroTrustDeviceRevokeNewResponse()                                   {}
func (UnionString) ImplementsZeroTrustDeviceUnrevokeNewResponse()                                 {}
func (UnionString) ImplementsZeroTrustAccessApplicationUpdateParamsAppID()                        {}
func (UnionString) ImplementsZeroTrustAccessApplicationDeleteParamsAppID()                        {}
func (UnionString) ImplementsZeroTrustAccessApplicationGetParamsAppID()                           {}
func (UnionString) ImplementsZeroTrustAccessApplicationRevokeTokensParamsAppID()                  {}
func (UnionString) ImplementsZeroTrustAccessApplicationCANewResponse()                            {}
func (UnionString) ImplementsZeroTrustAccessApplicationCAGetResponse()                            {}
func (UnionString) ImplementsZeroTrustAccessApplicationUserPolicyCheckListParamsAppID()           {}
func (UnionString) ImplementsZeroTrustAccessKeyUpdateResponse()                                   {}
func (UnionString) ImplementsZeroTrustAccessKeyListResponse()                                     {}
func (UnionString) ImplementsZeroTrustAccessKeyRotateResponse()                                   {}
func (UnionString) ImplementsZeroTrustTunnelConfigurationUpdateResponse()                         {}
func (UnionString) ImplementsZeroTrustTunnelConfigurationGetResponse()                            {}
func (UnionString) ImplementsZeroTrustTunnelConnectionDeleteResponse()                            {}
func (UnionString) ImplementsZeroTrustTunnelTokenGetResponse()                                    {}
func (UnionString) ImplementsZeroTrustTunnelManagementNewResponse()                               {}
func (UnionString) ImplementsZeroTrustDLPProfileCustomDeleteResponse()                            {}
func (UnionString) ImplementsZeroTrustGatewayListDeleteResponse()                                 {}
func (UnionString) ImplementsZeroTrustGatewayLocationDeleteResponse()                             {}
func (UnionString) ImplementsZeroTrustGatewayProxyEndpointDeleteResponse()                        {}
func (UnionString) ImplementsZeroTrustGatewayRuleDeleteResponse()                                 {}
func (UnionString) ImplementsZeroTrustNetworkVirtualNetworkNewResponse()                          {}
func (UnionString) ImplementsZeroTrustNetworkVirtualNetworkDeleteResponse()                       {}
func (UnionString) ImplementsZeroTrustNetworkVirtualNetworkEditResponse()                         {}
func (UnionString) ImplementsHyperdriveConfigDeleteResponse()                                     {}
func (UnionString) ImplementsVectorizeIndexDeleteResponse()                                       {}
func (UnionString) ImplementsRadarRankingTimeseriesGroupsResponseSerie0()                         {}
func (UnionString) ImplementsOriginPostQuantumEncryptionUpdateResponse()                          {}
func (UnionString) ImplementsOriginPostQuantumEncryptionGetResponse()                             {}
func (UnionString) ImplementsHostnameSettingTLSUpdateResponseValue()                              {}
func (UnionString) ImplementsHostnameSettingTLSGetResponseValue()                                 {}
func (UnionString) ImplementsHostnameSettingTLSUpdateParamsValue()                                {}
func (UnionString) ImplementsSnippetDeleteResponse()                                              {}
func (UnionString) ImplementsCloudforceOneRequestDeleteResponse()                                 {}
func (UnionString) ImplementsCloudforceOneRequestMessageDeleteResponse()                          {}
func (UnionString) ImplementsCloudforceOneRequestPriorityDeleteResponse()                         {}

type UnionInt int64

func (UnionInt) ImplementsLogReceivedGetParamsEnd()             {}
func (UnionInt) ImplementsLogReceivedGetParamsStart()           {}
func (UnionInt) ImplementsSpectrumAppNewResponseOriginPort()    {}
func (UnionInt) ImplementsSpectrumAppUpdateResponseOriginPort() {}
func (UnionInt) ImplementsSpectrumAppNewParamsOriginPort()      {}
func (UnionInt) ImplementsSpectrumAppUpdateParamsOriginPort()   {}
func (UnionInt) ImplementsRuleListItemGetResponse()             {}

type UnionFloat float64

func (UnionFloat) ImplementsDNSRecordNewResponseAttl()                   {}
func (UnionFloat) ImplementsDNSRecordNewResponseAaaattl()                {}
func (UnionFloat) ImplementsDNSRecordNewResponseCaattl()                 {}
func (UnionFloat) ImplementsDNSRecordNewResponseCertTTL()                {}
func (UnionFloat) ImplementsDNSRecordNewResponseCnamettl()               {}
func (UnionFloat) ImplementsDNSRecordNewResponseDnskeyttl()              {}
func (UnionFloat) ImplementsDNSRecordNewResponseDsttl()                  {}
func (UnionFloat) ImplementsDNSRecordNewResponseHttpsttl()               {}
func (UnionFloat) ImplementsDNSRecordNewResponseLocttl()                 {}
func (UnionFloat) ImplementsDNSRecordNewResponseMxttl()                  {}
func (UnionFloat) ImplementsDNSRecordNewResponseNaptrttl()               {}
func (UnionFloat) ImplementsDNSRecordNewResponseNsttl()                  {}
func (UnionFloat) ImplementsDNSRecordNewResponsePtrttl()                 {}
func (UnionFloat) ImplementsDNSRecordNewResponseSmimeaTTL()              {}
func (UnionFloat) ImplementsDNSRecordNewResponseSrvttl()                 {}
func (UnionFloat) ImplementsDNSRecordNewResponseSshfpttl()               {}
func (UnionFloat) ImplementsDNSRecordNewResponseSvcbttl()                {}
func (UnionFloat) ImplementsDNSRecordNewResponseTlsattl()                {}
func (UnionFloat) ImplementsDNSRecordNewResponseTxtttl()                 {}
func (UnionFloat) ImplementsDNSRecordNewResponseUrittl()                 {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseAttl()                {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseAaaattl()             {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseCaattl()              {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseCertTTL()             {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseCnamettl()            {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDnskeyttl()           {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDsttl()               {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseHttpsttl()            {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseLocttl()              {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseMxttl()               {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseNaptrttl()            {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseNsttl()               {}
func (UnionFloat) ImplementsDNSRecordUpdateResponsePtrttl()              {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseSmimeaTTL()           {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseSrvttl()              {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseSshfpttl()            {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseSvcbttl()             {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseTlsattl()             {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseTxtttl()              {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseUrittl()              {}
func (UnionFloat) ImplementsDNSRecordListResponseAttl()                  {}
func (UnionFloat) ImplementsDNSRecordListResponseAaaattl()               {}
func (UnionFloat) ImplementsDNSRecordListResponseCaattl()                {}
func (UnionFloat) ImplementsDNSRecordListResponseCertTTL()               {}
func (UnionFloat) ImplementsDNSRecordListResponseCnamettl()              {}
func (UnionFloat) ImplementsDNSRecordListResponseDnskeyttl()             {}
func (UnionFloat) ImplementsDNSRecordListResponseDsttl()                 {}
func (UnionFloat) ImplementsDNSRecordListResponseHttpsttl()              {}
func (UnionFloat) ImplementsDNSRecordListResponseLocttl()                {}
func (UnionFloat) ImplementsDNSRecordListResponseMxttl()                 {}
func (UnionFloat) ImplementsDNSRecordListResponseNaptrttl()              {}
func (UnionFloat) ImplementsDNSRecordListResponseNsttl()                 {}
func (UnionFloat) ImplementsDNSRecordListResponsePtrttl()                {}
func (UnionFloat) ImplementsDNSRecordListResponseSmimeaTTL()             {}
func (UnionFloat) ImplementsDNSRecordListResponseSrvttl()                {}
func (UnionFloat) ImplementsDNSRecordListResponseSshfpttl()              {}
func (UnionFloat) ImplementsDNSRecordListResponseSvcbttl()               {}
func (UnionFloat) ImplementsDNSRecordListResponseTlsattl()               {}
func (UnionFloat) ImplementsDNSRecordListResponseTxtttl()                {}
func (UnionFloat) ImplementsDNSRecordListResponseUrittl()                {}
func (UnionFloat) ImplementsDNSRecordEditResponseAttl()                  {}
func (UnionFloat) ImplementsDNSRecordEditResponseAaaattl()               {}
func (UnionFloat) ImplementsDNSRecordEditResponseCaattl()                {}
func (UnionFloat) ImplementsDNSRecordEditResponseCertTTL()               {}
func (UnionFloat) ImplementsDNSRecordEditResponseCnamettl()              {}
func (UnionFloat) ImplementsDNSRecordEditResponseDnskeyttl()             {}
func (UnionFloat) ImplementsDNSRecordEditResponseDsttl()                 {}
func (UnionFloat) ImplementsDNSRecordEditResponseHttpsttl()              {}
func (UnionFloat) ImplementsDNSRecordEditResponseLocttl()                {}
func (UnionFloat) ImplementsDNSRecordEditResponseMxttl()                 {}
func (UnionFloat) ImplementsDNSRecordEditResponseNaptrttl()              {}
func (UnionFloat) ImplementsDNSRecordEditResponseNsttl()                 {}
func (UnionFloat) ImplementsDNSRecordEditResponsePtrttl()                {}
func (UnionFloat) ImplementsDNSRecordEditResponseSmimeaTTL()             {}
func (UnionFloat) ImplementsDNSRecordEditResponseSrvttl()                {}
func (UnionFloat) ImplementsDNSRecordEditResponseSshfpttl()              {}
func (UnionFloat) ImplementsDNSRecordEditResponseSvcbttl()               {}
func (UnionFloat) ImplementsDNSRecordEditResponseTlsattl()               {}
func (UnionFloat) ImplementsDNSRecordEditResponseTxtttl()                {}
func (UnionFloat) ImplementsDNSRecordEditResponseUrittl()                {}
func (UnionFloat) ImplementsDNSRecordGetResponseAttl()                   {}
func (UnionFloat) ImplementsDNSRecordGetResponseAaaattl()                {}
func (UnionFloat) ImplementsDNSRecordGetResponseCaattl()                 {}
func (UnionFloat) ImplementsDNSRecordGetResponseCertTTL()                {}
func (UnionFloat) ImplementsDNSRecordGetResponseCnamettl()               {}
func (UnionFloat) ImplementsDNSRecordGetResponseDnskeyttl()              {}
func (UnionFloat) ImplementsDNSRecordGetResponseDsttl()                  {}
func (UnionFloat) ImplementsDNSRecordGetResponseHttpsttl()               {}
func (UnionFloat) ImplementsDNSRecordGetResponseLocttl()                 {}
func (UnionFloat) ImplementsDNSRecordGetResponseMxttl()                  {}
func (UnionFloat) ImplementsDNSRecordGetResponseNaptrttl()               {}
func (UnionFloat) ImplementsDNSRecordGetResponseNsttl()                  {}
func (UnionFloat) ImplementsDNSRecordGetResponsePtrttl()                 {}
func (UnionFloat) ImplementsDNSRecordGetResponseSmimeaTTL()              {}
func (UnionFloat) ImplementsDNSRecordGetResponseSrvttl()                 {}
func (UnionFloat) ImplementsDNSRecordGetResponseSshfpttl()               {}
func (UnionFloat) ImplementsDNSRecordGetResponseSvcbttl()                {}
func (UnionFloat) ImplementsDNSRecordGetResponseTlsattl()                {}
func (UnionFloat) ImplementsDNSRecordGetResponseTxtttl()                 {}
func (UnionFloat) ImplementsDNSRecordGetResponseUrittl()                 {}
func (UnionFloat) ImplementsDNSRecordNewParamsTTL()                      {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsTTL()                   {}
func (UnionFloat) ImplementsDNSRecordEditParamsTTL()                     {}
func (UnionFloat) ImplementsEmailRoutingRoutingDNSGetResponseTTL()       {}
func (UnionFloat) ImplementsRadarRankingTimeseriesGroupsResponseSerie0() {}
func (UnionFloat) ImplementsHostnameSettingTLSUpdateResponseValue()      {}
func (UnionFloat) ImplementsHostnameSettingTLSGetResponseValue()         {}
func (UnionFloat) ImplementsHostnameSettingTLSUpdateParamsValue()        {}
