// File generated from our OpenAPI spec by Stainless.

package shared

type UnionString string

func (UnionString) ImplementsAccountUpdateResponse()                                              {}
func (UnionString) ImplementsAccountGetResponse()                                                 {}
func (UnionString) ImplementsAccountRoleGetResponse()                                             {}
func (UnionString) ImplementsCertificateNewResponse()                                             {}
func (UnionString) ImplementsCertificateGetResponse()                                             {}
func (UnionString) ImplementsMembershipUpdateResponse()                                           {}
func (UnionString) ImplementsMembershipGetResponse()                                              {}
func (UnionString) ImplementsUserEditResponse()                                                   {}
func (UnionString) ImplementsUserGetResponse()                                                    {}
func (UnionString) ImplementsUserAuditLogListResponse()                                           {}
func (UnionString) ImplementsUserBillingProfileGetResponse()                                      {}
func (UnionString) ImplementsUserInviteEditResponse()                                             {}
func (UnionString) ImplementsUserInviteGetResponse()                                              {}
func (UnionString) ImplementsUserLoadBalancerPoolHealthResponse()                                 {}
func (UnionString) ImplementsUserOrganizationGetResponse()                                        {}
func (UnionString) ImplementsUserSubscriptionUpdateResponse()                                     {}
func (UnionString) ImplementsUserSubscriptionEditResponse()                                       {}
func (UnionString) ImplementsUserTokenUpdateResponse()                                            {}
func (UnionString) ImplementsUserTokenGetResponse()                                               {}
func (UnionString) ImplementsZoneCustomNameserverUpdateResponse()                                 {}
func (UnionString) ImplementsZoneCustomNameserverGetResponse()                                    {}
func (UnionString) ImplementsZoneWorkerScriptUpdateResponse()                                     {}
func (UnionString) ImplementsZoneSubscriptionNewResponse()                                        {}
func (UnionString) ImplementsZoneSubscriptionGetResponse()                                        {}
func (UnionString) ImplementsLoadBalancerPoolHealthGetResponse()                                  {}
func (UnionString) ImplementsLoadBalancerRegionListResponse()                                     {}
func (UnionString) ImplementsLoadBalancerRegionGetResponse()                                      {}
func (UnionString) ImplementsCachePurgeParamsFile()                                               {}
func (UnionString) ImplementsCacheSmartTieredCachedDeleteResponse()                               {}
func (UnionString) ImplementsCacheSmartTieredCachedEditResponse()                                 {}
func (UnionString) ImplementsCacheSmartTieredCachedGetResponse()                                  {}
func (UnionString) ImplementsSSLAnalyzeNewResponse()                                              {}
func (UnionString) ImplementsSSLCertificatePackGetResponse()                                      {}
func (UnionString) ImplementsSubscriptionNewResponse()                                            {}
func (UnionString) ImplementsSubscriptionUpdateResponse()                                         {}
func (UnionString) ImplementsSubscriptionGetResponse()                                            {}
func (UnionString) ImplementsArgoSmartRoutingEditResponse()                                       {}
func (UnionString) ImplementsArgoSmartRoutingGetResponse()                                        {}
func (UnionString) ImplementsArgoTieredCachingEditResponse()                                      {}
func (UnionString) ImplementsArgoTieredCachingGetResponse()                                       {}
func (UnionString) ImplementsCustomCertificateNewResponse()                                       {}
func (UnionString) ImplementsCustomCertificateEditResponse()                                      {}
func (UnionString) ImplementsCustomCertificateGetResponse()                                       {}
func (UnionString) ImplementsCustomHostnameFallbackOriginUpdateResponse()                         {}
func (UnionString) ImplementsCustomHostnameFallbackOriginDeleteResponse()                         {}
func (UnionString) ImplementsCustomHostnameFallbackOriginGetResponse()                            {}
func (UnionString) ImplementsCustomNameserverDeleteResponse()                                     {}
func (UnionString) ImplementsDNSFirewallNewResponseDNSFirewallIP()                                {}
func (UnionString) ImplementsDNSFirewallNewResponseUpstreamIP()                                   {}
func (UnionString) ImplementsDNSFirewallListResponseDNSFirewallIP()                               {}
func (UnionString) ImplementsDNSFirewallListResponseUpstreamIP()                                  {}
func (UnionString) ImplementsDNSFirewallEditResponseDNSFirewallIP()                               {}
func (UnionString) ImplementsDNSFirewallEditResponseUpstreamIP()                                  {}
func (UnionString) ImplementsDNSFirewallGetResponseDNSFirewallIP()                                {}
func (UnionString) ImplementsDNSFirewallGetResponseUpstreamIP()                                   {}
func (UnionString) ImplementsDNSFirewallNewParamsUpstreamIP()                                     {}
func (UnionString) ImplementsDNSFirewallEditParamsDNSFirewallIP()                                 {}
func (UnionString) ImplementsDNSFirewallEditParamsUpstreamIP()                                    {}
func (UnionString) ImplementsDNSSECDeleteResponse()                                               {}
func (UnionString) ImplementsFirewallAccessRuleNewResponse()                                      {}
func (UnionString) ImplementsFirewallAccessRuleEditResponse()                                     {}
func (UnionString) ImplementsFirewallAccessRuleGetResponse()                                      {}
func (UnionString) ImplementsFirewallUARuleNewResponse()                                          {}
func (UnionString) ImplementsFirewallUARuleUpdateResponse()                                       {}
func (UnionString) ImplementsFirewallUARuleGetResponse()                                          {}
func (UnionString) ImplementsFirewallWAFPackageListResponseLegacyJhsAPIResponseCollectionResult() {}
func (UnionString) ImplementsFirewallWAFPackageGetResponseLegacyJhsAPIResponseSingleResult()      {}
func (UnionString) ImplementsFirewallWAFPackageGroupEditResponse()                                {}
func (UnionString) ImplementsFirewallWAFPackageGroupGetResponse()                                 {}
func (UnionString) ImplementsFirewallWAFPackageRuleGetResponse()                                  {}
func (UnionString) ImplementsLogpushJobDeleteResponse()                                           {}
func (UnionString) ImplementsLogControlCmbConfigDeleteResponse()                                  {}
func (UnionString) ImplementsLogRayidGetResponse()                                                {}
func (UnionString) ImplementsLogReceivedGetResponse()                                             {}
func (UnionString) ImplementsLogReceivedGetParamsEnd()                                            {}
func (UnionString) ImplementsLogReceivedGetParamsStart()                                          {}
func (UnionString) ImplementsOriginTLSClientAuthNewResponse()                                     {}
func (UnionString) ImplementsOriginTLSClientAuthDeleteResponse()                                  {}
func (UnionString) ImplementsOriginTLSClientAuthGetResponse()                                     {}
func (UnionString) ImplementsPageruleNewResponse()                                                {}
func (UnionString) ImplementsPageruleUpdateResponse()                                             {}
func (UnionString) ImplementsPageruleEditResponse()                                               {}
func (UnionString) ImplementsPageruleGetResponse()                                                {}
func (UnionString) ImplementsRateLimitNewResponse()                                               {}
func (UnionString) ImplementsRateLimitEditResponse()                                              {}
func (UnionString) ImplementsRateLimitGetResponse()                                               {}
func (UnionString) ImplementsWorkerScriptTailDeleteResponse()                                     {}
func (UnionString) ImplementsWorkerRouteNewResponse()                                             {}
func (UnionString) ImplementsWorkerRouteDeleteResponse()                                          {}
func (UnionString) ImplementsKVNamespaceUpdateResponse()                                          {}
func (UnionString) ImplementsKVNamespaceDeleteResponse()                                          {}
func (UnionString) ImplementsKVNamespaceBulkUpdateResponse()                                      {}
func (UnionString) ImplementsKVNamespaceBulkDeleteResponse()                                      {}
func (UnionString) ImplementsKVNamespaceValueUpdateResponse()                                     {}
func (UnionString) ImplementsKVNamespaceValueDeleteResponse()                                     {}
func (UnionString) ImplementsQueueDeleteResponse()                                                {}
func (UnionString) ImplementsQueueConsumerDeleteResponse()                                        {}
func (UnionString) ImplementsSpectrumAnalyticsEventBytimeGetResponse()                            {}
func (UnionString) ImplementsSpectrumAnalyticsEventSummaryGetResponse()                           {}
func (UnionString) ImplementsSpectrumAppNewResponseOriginPort()                                   {}
func (UnionString) ImplementsSpectrumAppUpdateResponseOriginPort()                                {}
func (UnionString) ImplementsSpectrumAppGetResponse()                                             {}
func (UnionString) ImplementsSpectrumAppNewParamsOriginPort()                                     {}
func (UnionString) ImplementsSpectrumAppUpdateParamsOriginPort()                                  {}
func (UnionString) ImplementsAddressingAddressMapDeleteResponse()                                 {}
func (UnionString) ImplementsAddressingAddressMapAccountUpdateResponse()                          {}
func (UnionString) ImplementsAddressingAddressMapAccountDeleteResponse()                          {}
func (UnionString) ImplementsAddressingAddressMapIPUpdateResponse()                               {}
func (UnionString) ImplementsAddressingAddressMapIPDeleteResponse()                               {}
func (UnionString) ImplementsAddressingAddressMapZoneUpdateResponse()                             {}
func (UnionString) ImplementsAddressingAddressMapZoneDeleteResponse()                             {}
func (UnionString) ImplementsAddressingPrefixDeleteResponse()                                     {}
func (UnionString) ImplementsAddressingPrefixBGPBindingDeleteResponse()                           {}
func (UnionString) ImplementsAuditLogListResponse()                                               {}
func (UnionString) ImplementsBillingProfileGetResponse()                                          {}
func (UnionString) ImplementsImageV1NewResponseVariant()                                          {}
func (UnionString) ImplementsImageV1ListResponseResultImagesVariant()                             {}
func (UnionString) ImplementsImageV1DeleteResponse()                                              {}
func (UnionString) ImplementsImageV1EditResponseVariant()                                         {}
func (UnionString) ImplementsImageV1GetResponseVariant()                                          {}
func (UnionString) ImplementsImageV1VariantDeleteResponse()                                       {}
func (UnionString) ImplementsImageV2ListResponseImagesVariant()                                   {}
func (UnionString) ImplementsIntelIPGetResponseIP()                                               {}
func (UnionString) ImplementsIntelMiscategorizationNewResponse()                                  {}
func (UnionString) ImplementsPageProjectNewResponse()                                             {}
func (UnionString) ImplementsPageProjectEditResponse()                                            {}
func (UnionString) ImplementsPageProjectDeploymentHistoryLogGetResponse()                         {}
func (UnionString) ImplementsPageProjectDomainNewResponse()                                       {}
func (UnionString) ImplementsPageProjectDomainEditResponse()                                      {}
func (UnionString) ImplementsPageProjectDomainGetResponse()                                       {}
func (UnionString) ImplementsRegistrarDomainUpdateResponse()                                      {}
func (UnionString) ImplementsRegistrarDomainGetResponse()                                         {}
func (UnionString) ImplementsRuleListItemGetResponse()                                            {}
func (UnionString) ImplementsStreamAudioTrackDeleteResponse()                                     {}
func (UnionString) ImplementsStreamKeyDeleteResponse()                                            {}
func (UnionString) ImplementsStreamWatermarkNewResponse()                                         {}
func (UnionString) ImplementsStreamWatermarkDeleteResponse()                                      {}
func (UnionString) ImplementsStreamWatermarkGetResponse()                                         {}
func (UnionString) ImplementsStreamWebhookUpdateResponse()                                        {}
func (UnionString) ImplementsStreamWebhookDeleteResponse()                                        {}
func (UnionString) ImplementsStreamWebhookGetResponse()                                           {}
func (UnionString) ImplementsStreamCaptionUpdateResponse()                                        {}
func (UnionString) ImplementsStreamCaptionDeleteResponse()                                        {}
func (UnionString) ImplementsStreamDownloadNewResponse()                                          {}
func (UnionString) ImplementsStreamDownloadDeleteResponse()                                       {}
func (UnionString) ImplementsStreamDownloadGetResponse()                                          {}
func (UnionString) ImplementsAlertingV3ListResponse()                                             {}
func (UnionString) ImplementsAlertingV3DestinationEligibleGetResponse()                           {}
func (UnionString) ImplementsAlertingV3DestinationPagerdutyDeleteResponse()                       {}
func (UnionString) ImplementsAlertingV3DestinationWebhookDeleteResponse()                         {}
func (UnionString) ImplementsAlertingV3PolicyListResponseMechanismsID()                           {}
func (UnionString) ImplementsAlertingV3PolicyDeleteResponse()                                     {}
func (UnionString) ImplementsAlertingV3PolicyGetResponseMechanismsID()                            {}
func (UnionString) ImplementsAlertingV3PolicyNewParamsMechanismsID()                              {}
func (UnionString) ImplementsAlertingV3PolicyUpdateParamsMechanismsID()                           {}
func (UnionString) ImplementsD1DatabaseDeleteResponse()                                           {}
func (UnionString) ImplementsWARPConnectorTokenResponse()                                         {}
func (UnionString) ImplementsZeroTrustDeviceGetResponse()                                         {}
func (UnionString) ImplementsZeroTrustDevicePostureIntegrationDeleteResponse()                    {}
func (UnionString) ImplementsZeroTrustDeviceRevokeNewResponse()                                   {}
func (UnionString) ImplementsZeroTrustDeviceUnrevokeNewResponse()                                 {}
func (UnionString) ImplementsZeroTrustAccessApplicationUpdateParamsAppID()                        {}
func (UnionString) ImplementsZeroTrustAccessApplicationDeleteParamsAppID()                        {}
func (UnionString) ImplementsZeroTrustAccessApplicationGetParamsAppID()                           {}
func (UnionString) ImplementsZeroTrustAccessApplicationRevokeTokensParamsAppID()                  {}
func (UnionString) ImplementsZeroTrustAccessApplicationCANewResponse()                            {}
func (UnionString) ImplementsZeroTrustAccessApplicationCAGetResponse()                            {}
func (UnionString) ImplementsZeroTrustAccessApplicationUserPolicyCheckListParamsAppID()           {}
func (UnionString) ImplementsZeroTrustAccessKeyUpdateResponse()                                   {}
func (UnionString) ImplementsZeroTrustAccessKeyListResponse()                                     {}
func (UnionString) ImplementsZeroTrustAccessKeyRotateResponse()                                   {}
func (UnionString) ImplementsZeroTrustTunnelConfigurationUpdateResponse()                         {}
func (UnionString) ImplementsZeroTrustTunnelConfigurationGetResponse()                            {}
func (UnionString) ImplementsZeroTrustTunnelConnectionDeleteResponse()                            {}
func (UnionString) ImplementsZeroTrustTunnelTokenGetResponse()                                    {}
func (UnionString) ImplementsZeroTrustTunnelManagementNewResponse()                               {}
func (UnionString) ImplementsZeroTrustDLPProfileCustomDeleteResponse()                            {}
func (UnionString) ImplementsZeroTrustGatewayListDeleteResponse()                                 {}
func (UnionString) ImplementsZeroTrustGatewayLocationDeleteResponse()                             {}
func (UnionString) ImplementsZeroTrustGatewayProxyEndpointDeleteResponse()                        {}
func (UnionString) ImplementsZeroTrustGatewayRuleDeleteResponse()                                 {}
func (UnionString) ImplementsZeroTrustNetworkVirtualNetworkNewResponse()                          {}
func (UnionString) ImplementsZeroTrustNetworkVirtualNetworkDeleteResponse()                       {}
func (UnionString) ImplementsZeroTrustNetworkVirtualNetworkEditResponse()                         {}
func (UnionString) ImplementsHyperdriveConfigDeleteResponse()                                     {}
func (UnionString) ImplementsVectorizeIndexDeleteResponse()                                       {}
func (UnionString) ImplementsRadarRankingTimeseriesGroupsResponseSerie0()                         {}
func (UnionString) ImplementsOriginPostQuantumEncryptionUpdateResponse()                          {}
func (UnionString) ImplementsOriginPostQuantumEncryptionGetResponse()                             {}
func (UnionString) ImplementsHostnameSettingTLSUpdateResponseValue()                              {}
func (UnionString) ImplementsHostnameSettingTLSGetResponseValue()                                 {}
func (UnionString) ImplementsHostnameSettingTLSUpdateParamsValue()                                {}
func (UnionString) ImplementsSnippetDeleteResponse()                                              {}
func (UnionString) ImplementsCloudforceOneRequestDeleteResponse()                                 {}
func (UnionString) ImplementsCloudforceOneRequestMessageDeleteResponse()                          {}
func (UnionString) ImplementsCloudforceOneRequestPriorityDeleteResponse()                         {}

type UnionInt int64

func (UnionInt) ImplementsLogReceivedGetParamsEnd()             {}
func (UnionInt) ImplementsLogReceivedGetParamsStart()           {}
func (UnionInt) ImplementsSpectrumAppNewResponseOriginPort()    {}
func (UnionInt) ImplementsSpectrumAppUpdateResponseOriginPort() {}
func (UnionInt) ImplementsSpectrumAppNewParamsOriginPort()      {}
func (UnionInt) ImplementsSpectrumAppUpdateParamsOriginPort()   {}
func (UnionInt) ImplementsRuleListItemGetResponse()             {}

type UnionFloat float64

func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsARecordTTL()         {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsAAAARecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsCAARecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsCertRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsCNAMERecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsDNSKEYRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsDSRecordTTL()        {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsHTTPSRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsLOCRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsMXRecordTTL()        {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsNAPTRRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsNSRecordTTL()        {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsPTRRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsSmimeaRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsSRVRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsSSHFPRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsSVCBRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsTLSARecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsTXTRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordNewResponseDNSRecordsURIRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsARecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsAAAARecordTTL()   {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsCAARecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsCertRecordTTL()   {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsCNAMERecordTTL()  {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsDNSKEYRecordTTL() {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsDSRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsHTTPSRecordTTL()  {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsLOCRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsMXRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsNAPTRRecordTTL()  {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsNSRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsPTRRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsSmimeaRecordTTL() {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsSRVRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsSSHFPRecordTTL()  {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsSVCBRecordTTL()   {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsTLSARecordTTL()   {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsTXTRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordUpdateResponseDNSRecordsURIRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsARecordTTL()        {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsAAAARecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsCAARecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsCertRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsCNAMERecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsDNSKEYRecordTTL()   {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsDSRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsHTTPSRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsLOCRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsMXRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsNAPTRRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsNSRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsPTRRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsSmimeaRecordTTL()   {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsSRVRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsSSHFPRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsSVCBRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsTLSARecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsTXTRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordListResponseDNSRecordsURIRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsARecordTTL()        {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsAAAARecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsCAARecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsCertRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsCNAMERecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsDNSKEYRecordTTL()   {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsDSRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsHTTPSRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsLOCRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsMXRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsNAPTRRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsNSRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsPTRRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsSmimeaRecordTTL()   {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsSRVRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsSSHFPRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsSVCBRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsTLSARecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsTXTRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordEditResponseDNSRecordsURIRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsARecordTTL()         {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsAAAARecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsCAARecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsCertRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsCNAMERecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsDNSKEYRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsDSRecordTTL()        {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsHTTPSRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsLOCRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsMXRecordTTL()        {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsNAPTRRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsNSRecordTTL()        {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsPTRRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsSmimeaRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsSRVRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsSSHFPRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsSVCBRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsTLSARecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsTXTRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordGetResponseDNSRecordsURIRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordNewParamsTTL()                            {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsTTL()                         {}
func (UnionFloat) ImplementsDNSRecordEditParamsTTL()                           {}
func (UnionFloat) ImplementsEmailRoutingRoutingDNSGetResponseTTL()             {}
func (UnionFloat) ImplementsRadarRankingTimeseriesGroupsResponseSerie0()       {}
func (UnionFloat) ImplementsHostnameSettingTLSUpdateResponseValue()            {}
func (UnionFloat) ImplementsHostnameSettingTLSGetResponseValue()               {}
func (UnionFloat) ImplementsHostnameSettingTLSUpdateParamsValue()              {}
