// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package shared

type UnionString string

func (UnionString) ImplementsSharedUnnamedSchemaRef116()                                         {}
func (UnionString) ImplementsSharedUnnamedSchemaRef121Param()                                    {}
func (UnionString) ImplementsSharedUnnamedSchemaRef161()                                         {}
func (UnionString) ImplementsSharedUnnamedSchemaRef167()                                         {}
func (UnionString) ImplementsSharedUnnamedSchemaRef169()                                         {}
func (UnionString) ImplementsSharedUnnamedSchemaRef171()                                         {}
func (UnionString) ImplementsSharedUnnamedSchemaRef173()                                         {}
func (UnionString) ImplementsSharedUnnamedSchemaRef49()                                          {}
func (UnionString) ImplementsSharedUnnamedSchemaRef65Value()                                     {}
func (UnionString) ImplementsAccountsAccountUpdateResponse()                                     {}
func (UnionString) ImplementsAccountsAccountGetResponse()                                        {}
func (UnionString) ImplementsAccountsRoleGetResponse()                                           {}
func (UnionString) ImplementsOriginCACertificatesOriginCACertificateNewResponse()                {}
func (UnionString) ImplementsOriginCACertificatesOriginCACertificateGetResponse()                {}
func (UnionString) ImplementsMembershipsMembershipUpdateResponse()                               {}
func (UnionString) ImplementsMembershipsMembershipGetResponse()                                  {}
func (UnionString) ImplementsUserUserEditResponse()                                              {}
func (UnionString) ImplementsUserUserGetResponse()                                               {}
func (UnionString) ImplementsUserBillingProfileGetResponse()                                     {}
func (UnionString) ImplementsUserInviteEditResponse()                                            {}
func (UnionString) ImplementsUserInviteGetResponse()                                             {}
func (UnionString) ImplementsUserLoadBalancerPoolHealthResponse()                                {}
func (UnionString) ImplementsUserOrganizationGetResponse()                                       {}
func (UnionString) ImplementsUserSubscriptionUpdateResponse()                                    {}
func (UnionString) ImplementsUserSubscriptionEditResponse()                                      {}
func (UnionString) ImplementsUserTokenUpdateResponse()                                           {}
func (UnionString) ImplementsUserTokenGetResponse()                                              {}
func (UnionString) ImplementsZonesCustomNameserverUpdateResponse()                               {}
func (UnionString) ImplementsZonesWorkerScriptUpdateResponse()                                   {}
func (UnionString) ImplementsZonesSubscriptionNewResponse()                                      {}
func (UnionString) ImplementsZonesSubscriptionGetResponse()                                      {}
func (UnionString) ImplementsLoadBalancersPoolHealthGetResponse()                                {}
func (UnionString) ImplementsLoadBalancersRegionListResponse()                                   {}
func (UnionString) ImplementsLoadBalancersRegionGetResponse()                                    {}
func (UnionString) ImplementsCacheCachePurgeParamsCachePurgeFilesFile()                          {}
func (UnionString) ImplementsCacheSmartTieredCacheDeleteResponse()                               {}
func (UnionString) ImplementsCacheSmartTieredCacheEditResponse()                                 {}
func (UnionString) ImplementsCacheSmartTieredCacheGetResponse()                                  {}
func (UnionString) ImplementsSSLAnalyzeNewResponse()                                             {}
func (UnionString) ImplementsSSLCertificatePackGetResponse()                                     {}
func (UnionString) ImplementsSubscriptionsSubscriptionNewResponse()                              {}
func (UnionString) ImplementsSubscriptionsSubscriptionUpdateResponse()                           {}
func (UnionString) ImplementsSubscriptionsSubscriptionGetResponse()                              {}
func (UnionString) ImplementsArgoSmartRoutingEditResponse()                                      {}
func (UnionString) ImplementsArgoSmartRoutingGetResponse()                                       {}
func (UnionString) ImplementsArgoTieredCachingEditResponse()                                     {}
func (UnionString) ImplementsArgoTieredCachingGetResponse()                                      {}
func (UnionString) ImplementsCustomCertificatesCustomCertificateNewResponse()                    {}
func (UnionString) ImplementsCustomCertificatesCustomCertificateEditResponse()                   {}
func (UnionString) ImplementsCustomCertificatesCustomCertificateGetResponse()                    {}
func (UnionString) ImplementsCustomHostnamesFallbackOriginUpdateResponse()                       {}
func (UnionString) ImplementsCustomHostnamesFallbackOriginDeleteResponse()                       {}
func (UnionString) ImplementsCustomHostnamesFallbackOriginGetResponse()                          {}
func (UnionString) ImplementsCustomNameserversCustomNameserverDeleteResponse()                   {}
func (UnionString) ImplementsDNSDNSFirewallDNSFirewallIP()                                       {}
func (UnionString) ImplementsDNSDNSFirewallUpstreamIP()                                          {}
func (UnionString) ImplementsDNSFirewallNewParamsUpstreamIP()                                    {}
func (UnionString) ImplementsDNSFirewallEditParamsDNSFirewallIP()                                {}
func (UnionString) ImplementsDNSFirewallEditParamsUpstreamIP()                                   {}
func (UnionString) ImplementsFirewallWAFPackageGetResponseLegacyJhsAPIResponseSingleResult()     {}
func (UnionString) ImplementsFirewallWAFPackageGroupEditResponse()                               {}
func (UnionString) ImplementsFirewallWAFPackageGroupGetResponse()                                {}
func (UnionString) ImplementsFirewallWAFPackageRuleGetResponse()                                 {}
func (UnionString) ImplementsLogsRayIDGetResponse()                                              {}
func (UnionString) ImplementsLogsReceivedGetResponse()                                           {}
func (UnionString) ImplementsLogsReceivedGetParamsEnd()                                          {}
func (UnionString) ImplementsLogsReceivedGetParamsStart()                                        {}
func (UnionString) ImplementsOriginTLSClientAuthOriginTLSClientAuthNewResponse()                 {}
func (UnionString) ImplementsOriginTLSClientAuthOriginTLSClientAuthDeleteResponse()              {}
func (UnionString) ImplementsOriginTLSClientAuthOriginTLSClientAuthGetResponse()                 {}
func (UnionString) ImplementsPagerulesPageruleNewResponse()                                      {}
func (UnionString) ImplementsPagerulesPageruleUpdateResponse()                                   {}
func (UnionString) ImplementsPagerulesPageruleEditResponse()                                     {}
func (UnionString) ImplementsPagerulesPageruleGetResponse()                                      {}
func (UnionString) ImplementsWorkersAIRunResponse()                                              {}
func (UnionString) ImplementsWorkersRouteNewResponse()                                           {}
func (UnionString) ImplementsWorkersRouteDeleteResponse()                                        {}
func (UnionString) ImplementsKVNamespaceUpdateResponse()                                         {}
func (UnionString) ImplementsKVNamespaceDeleteResponse()                                         {}
func (UnionString) ImplementsKVNamespaceBulkUpdateResponse()                                     {}
func (UnionString) ImplementsKVNamespaceBulkDeleteResponse()                                     {}
func (UnionString) ImplementsKVNamespaceValueUpdateResponse()                                    {}
func (UnionString) ImplementsKVNamespaceValueDeleteResponse()                                    {}
func (UnionString) ImplementsSpectrumAnalyticsEventBytimeGetResponse()                           {}
func (UnionString) ImplementsSpectrumAnalyticsEventSummaryGetResponse()                          {}
func (UnionString) ImplementsSpectrumAppNewResponseOriginPort()                                  {}
func (UnionString) ImplementsSpectrumAppUpdateResponseOriginPort()                               {}
func (UnionString) ImplementsSpectrumAppNewParamsOriginPort()                                    {}
func (UnionString) ImplementsSpectrumAppUpdateParamsOriginPort()                                 {}
func (UnionString) ImplementsBillingProfileGetResponse()                                         {}
func (UnionString) ImplementsImagesImageVariant()                                                {}
func (UnionString) ImplementsImagesV1DeleteResponse()                                            {}
func (UnionString) ImplementsImagesV1VariantDeleteResponse()                                     {}
func (UnionString) ImplementsIntelIntelSchemasIpip()                                             {}
func (UnionString) ImplementsIntelMiscategorizationNewResponse()                                 {}
func (UnionString) ImplementsIntelAttackSurfaceReportIssueDismissResponse()                      {}
func (UnionString) ImplementsMagicTransitSiteACLNewResponseACLsLan1Subnet()                      {}
func (UnionString) ImplementsMagicTransitSiteACLNewResponseACLsLan2Subnet()                      {}
func (UnionString) ImplementsMagicTransitSiteACLUpdateResponseAcllan1Subnet()                    {}
func (UnionString) ImplementsMagicTransitSiteACLUpdateResponseAcllan2Subnet()                    {}
func (UnionString) ImplementsMagicTransitSiteACLListResponseACLsLan1Subnet()                     {}
func (UnionString) ImplementsMagicTransitSiteACLListResponseACLsLan2Subnet()                     {}
func (UnionString) ImplementsMagicTransitSiteACLDeleteResponseDeletedAcllan1Subnet()             {}
func (UnionString) ImplementsMagicTransitSiteACLDeleteResponseDeletedAcllan2Subnet()             {}
func (UnionString) ImplementsMagicTransitSiteACLGetResponseAcllan1Subnet()                       {}
func (UnionString) ImplementsMagicTransitSiteACLGetResponseAcllan2Subnet()                       {}
func (UnionString) ImplementsMagicTransitSiteACLNewParamsAcllan1Subnet()                         {}
func (UnionString) ImplementsMagicTransitSiteACLNewParamsAcllan2Subnet()                         {}
func (UnionString) ImplementsMagicTransitSiteACLUpdateParamsAcllan1Subnet()                      {}
func (UnionString) ImplementsMagicTransitSiteACLUpdateParamsAcllan2Subnet()                      {}
func (UnionString) ImplementsPagesProjectNewResponse()                                           {}
func (UnionString) ImplementsPagesProjectEditResponse()                                          {}
func (UnionString) ImplementsPagesProjectDeploymentHistoryLogGetResponse()                       {}
func (UnionString) ImplementsPagesProjectDomainNewResponse()                                     {}
func (UnionString) ImplementsPagesProjectDomainEditResponse()                                    {}
func (UnionString) ImplementsPagesProjectDomainGetResponse()                                     {}
func (UnionString) ImplementsRegistrarDomainUpdateResponse()                                     {}
func (UnionString) ImplementsRegistrarDomainGetResponse()                                        {}
func (UnionString) ImplementsRulesListItemGetResponse()                                          {}
func (UnionString) ImplementsStreamAudioTrackDeleteResponse()                                    {}
func (UnionString) ImplementsStreamKeyDeleteResponse()                                           {}
func (UnionString) ImplementsStreamWatermarkNewResponse()                                        {}
func (UnionString) ImplementsStreamWatermarkGetResponse()                                        {}
func (UnionString) ImplementsStreamWebhookUpdateResponse()                                       {}
func (UnionString) ImplementsStreamWebhookDeleteResponse()                                       {}
func (UnionString) ImplementsStreamWebhookGetResponse()                                          {}
func (UnionString) ImplementsStreamCaptionUpdateResponse()                                       {}
func (UnionString) ImplementsStreamCaptionDeleteResponse()                                       {}
func (UnionString) ImplementsStreamDownloadNewResponse()                                         {}
func (UnionString) ImplementsStreamDownloadDeleteResponse()                                      {}
func (UnionString) ImplementsStreamDownloadGetResponse()                                         {}
func (UnionString) ImplementsAlertingDestinationEligibleGetResponse()                            {}
func (UnionString) ImplementsAlertingAlertingPoliciesMechanismsID()                              {}
func (UnionString) ImplementsAlertingPolicyNewParamsMechanismsID()                               {}
func (UnionString) ImplementsAlertingPolicyUpdateParamsMechanismsID()                            {}
func (UnionString) ImplementsWARPConnectorWARPConnectorTokenResponse()                           {}
func (UnionString) ImplementsZeroTrustAccessApplicationUpdateParamsSelfHostedApplicationAppID()  {}
func (UnionString) ImplementsZeroTrustAccessApplicationUpdateParamsSaaSApplicationAppID()        {}
func (UnionString) ImplementsZeroTrustAccessApplicationUpdateParamsBrowserSSHApplicationAppID()  {}
func (UnionString) ImplementsZeroTrustAccessApplicationUpdateParamsBrowserVncApplicationAppID()  {}
func (UnionString) ImplementsZeroTrustAccessApplicationUpdateParamsAppLauncherApplicationAppID() {}
func (UnionString) ImplementsZeroTrustAccessApplicationUpdateParamsDeviceEnrollmentPermissionsApplicationAppID() {
}
func (UnionString) ImplementsZeroTrustAccessApplicationUpdateParamsBrowserIsolationPermissionsApplicationAppID() {
}
func (UnionString) ImplementsZeroTrustAccessApplicationUpdateParamsBookmarkApplicationAppID()       {}
func (UnionString) ImplementsZeroTrustAccessApplicationDeleteParamsAppID()                          {}
func (UnionString) ImplementsZeroTrustAccessApplicationGetParamsAppID()                             {}
func (UnionString) ImplementsZeroTrustAccessApplicationRevokeTokensParamsAppID()                    {}
func (UnionString) ImplementsZeroTrustAccessApplicationCANewResponse()                              {}
func (UnionString) ImplementsZeroTrustAccessApplicationCAGetResponse()                              {}
func (UnionString) ImplementsZeroTrustAccessApplicationUserPolicyCheckListParamsAppID()             {}
func (UnionString) ImplementsZeroTrustAccessKeyUpdateResponse()                                     {}
func (UnionString) ImplementsZeroTrustAccessKeyGetResponse()                                        {}
func (UnionString) ImplementsZeroTrustAccessKeyRotateResponse()                                     {}
func (UnionString) ImplementsZeroTrustTunnelConfigurationUpdateResponse()                           {}
func (UnionString) ImplementsZeroTrustTunnelConfigurationGetResponse()                              {}
func (UnionString) ImplementsZeroTrustTunnelConnectionDeleteResponse()                              {}
func (UnionString) ImplementsZeroTrustTunnelTokenGetResponse()                                      {}
func (UnionString) ImplementsZeroTrustTunnelManagementNewResponse()                                 {}
func (UnionString) ImplementsZeroTrustGatewayListDeleteResponse()                                   {}
func (UnionString) ImplementsZeroTrustGatewayLocationDeleteResponse()                               {}
func (UnionString) ImplementsZeroTrustGatewayProxyEndpointDeleteResponse()                          {}
func (UnionString) ImplementsZeroTrustGatewayRuleDeleteResponse()                                   {}
func (UnionString) ImplementsZeroTrustNetworkVirtualNetworkNewResponse()                            {}
func (UnionString) ImplementsZeroTrustNetworkVirtualNetworkDeleteResponse()                         {}
func (UnionString) ImplementsZeroTrustNetworkVirtualNetworkEditResponse()                           {}
func (UnionString) ImplementsRadarRankingTimeseriesGroupsResponseSerie0()                           {}
func (UnionString) ImplementsOriginPostQuantumEncryptionOriginPostQuantumEncryptionUpdateResponse() {}
func (UnionString) ImplementsOriginPostQuantumEncryptionOriginPostQuantumEncryptionGetResponse()    {}
func (UnionString) ImplementsHostnamesSettingTLSUpdateParamsValue()                                 {}

type UnionInt int64

func (UnionInt) ImplementsLogsReceivedGetParamsEnd()            {}
func (UnionInt) ImplementsLogsReceivedGetParamsStart()          {}
func (UnionInt) ImplementsSpectrumAppNewResponseOriginPort()    {}
func (UnionInt) ImplementsSpectrumAppUpdateResponseOriginPort() {}
func (UnionInt) ImplementsSpectrumAppNewParamsOriginPort()      {}
func (UnionInt) ImplementsSpectrumAppUpdateParamsOriginPort()   {}
func (UnionInt) ImplementsRulesListItemGetResponse()            {}

type UnionFloat float64

func (UnionFloat) ImplementsSharedUnnamedSchemaRef65Value()                  {}
func (UnionFloat) ImplementsDNSDNSRecordAttl()                               {}
func (UnionFloat) ImplementsDNSDNSRecordAaaattl()                            {}
func (UnionFloat) ImplementsDNSDNSRecordCaattl()                             {}
func (UnionFloat) ImplementsDNSDNSRecordCertttl()                            {}
func (UnionFloat) ImplementsDNSDNSRecordCnamettl()                           {}
func (UnionFloat) ImplementsDNSDNSRecordDnskeyttl()                          {}
func (UnionFloat) ImplementsDNSDNSRecordDsttl()                              {}
func (UnionFloat) ImplementsDNSDNSRecordHttpsttl()                           {}
func (UnionFloat) ImplementsDNSDNSRecordLocttl()                             {}
func (UnionFloat) ImplementsDNSDNSRecordMxttl()                              {}
func (UnionFloat) ImplementsDNSDNSRecordNaptrttl()                           {}
func (UnionFloat) ImplementsDNSDNSRecordNsttl()                              {}
func (UnionFloat) ImplementsDNSDNSRecordPtrttl()                             {}
func (UnionFloat) ImplementsDNSDNSRecordSmimeattl()                          {}
func (UnionFloat) ImplementsDNSDNSRecordSrvttl()                             {}
func (UnionFloat) ImplementsDNSDNSRecordSshfpttl()                           {}
func (UnionFloat) ImplementsDNSDNSRecordSvcbttl()                            {}
func (UnionFloat) ImplementsDNSDNSRecordTlsattl()                            {}
func (UnionFloat) ImplementsDNSDNSRecordTxtttl()                             {}
func (UnionFloat) ImplementsDNSDNSRecordUrittl()                             {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsARecordTTL()         {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsAAAARecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsCAARecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsCERTRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsCNAMERecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsDNSKEYRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsDSRecordTTL()        {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsHTTPSRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsLOCRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsMXRecordTTL()        {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsNAPTRRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsNSRecordTTL()        {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsPTRRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsSMIMEARecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsSRVRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsSSHFPRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsSVCBRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsTLSARecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsTXTRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordNewParamsDNSRecordsURIRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsARecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsAAAARecordTTL()   {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsCAARecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsCERTRecordTTL()   {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsCNAMERecordTTL()  {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsDNSKEYRecordTTL() {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsDSRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsHTTPSRecordTTL()  {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsLOCRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsMXRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsNAPTRRecordTTL()  {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsNSRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsPTRRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsSMIMEARecordTTL() {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsSRVRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsSSHFPRecordTTL()  {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsSVCBRecordTTL()   {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsTLSARecordTTL()   {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsTXTRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordUpdateParamsDNSRecordsURIRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsARecordTTL()        {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsAAAARecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsCAARecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsCERTRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsCNAMERecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsDNSKEYRecordTTL()   {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsDSRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsHTTPSRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsLOCRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsMXRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsNAPTRRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsNSRecordTTL()       {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsPTRRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsSMIMEARecordTTL()   {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsSRVRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsSSHFPRecordTTL()    {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsSVCBRecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsTLSARecordTTL()     {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsTXTRecordTTL()      {}
func (UnionFloat) ImplementsDNSRecordEditParamsDNSRecordsURIRecordTTL()      {}
func (UnionFloat) ImplementsEmailRoutingEmailDNSRecordTTL()                  {}
func (UnionFloat) ImplementsRadarRankingTimeseriesGroupsResponseSerie0()     {}
func (UnionFloat) ImplementsHostnamesSettingTLSUpdateParamsValue()           {}
